apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        cluster: 'production'
    
    rule_files:
    - "ml_rules.yml"
    
    scrape_configs:
    - job_name: 'ml-model-api'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - ml-production
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
    
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter:9100']
    
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
  
  ml_rules.yml: |
    groups:
    - name: ml_model_alerts
      rules:
      - alert: ModelPredictionLatencyHigh
        expr: histogram_quantile(0.95, ml_request_duration_seconds_bucket) > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "ML model prediction latency is high"
          description: "95th percentile latency is {{ $value }}s"
      
      - alert: ModelErrorRateHigh
        expr: rate(ml_requests_total{status="error"}[5m]) / rate(ml_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "ML model error rate is high"
          description: "Error rate is {{ $value | humanizePercentage }}"
      
      - alert: ModelPredictionDrift
        expr: abs(rate(ml_prediction_values_sum[1h]) / rate(ml_prediction_values_count[1h]) - 0.5) > 0.2
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Potential model drift detected"
          description: "Average prediction value has changed significantly"
      
      - alert: ModelServiceDown
        expr: up{job="ml-model-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "ML model service is down"
          description: "ML model service has been down for more than 1 minute"