trigger: none

resources:
  pipelines:
  - pipeline: ci-pipeline
    source: 'CI Pipeline'
    trigger:
      branches:
        include:
        - main

variables:
  containerRegistry: 'mlopsacr.azurecr.io'
  imageRepository: 'ml-model-api'

stages:
- stage: DeployProduction
  displayName: 'Deploy to Production'
  jobs:
  - deployment: DeployProduction
    displayName: 'Production Deployment'
    environment: 'production'
    strategy:
      canary:
        increments: [10, 25, 50, 100]
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: 'Deploy to Production'
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'production-k8s'
              namespace: 'ml-production'
              manifests: |
                infrastructure/kubernetes/namespace.yaml
                infrastructure/kubernetes/deployment.yaml
                infrastructure/kubernetes/service.yaml
                infrastructure/kubernetes/ingress.yaml
              containers: '$(containerRegistry)/$(imageRepository):$(resources.pipeline.ci-pipeline.runID)'
          
          - script: |
              # Health check
              kubectl wait --for=condition=available --timeout=600s deployment/ml-model-api -n ml-production
              
              # Performance test
              python tests/performance/load_test.py --endpoint https://ml-api.company.com --duration 60
            displayName: 'Production validation'
        
        on:
          failure:
            steps:
            - script: |
                kubectl rollout undo deployment/ml-model-api -n ml-production
                echo "Deployment failed, rolled back to previous version"
              displayName: 'Rollback on failure'
          
          success:
            steps:
            - script: |
                # Update model registry stage
                python src/utils/promote_model.py --stage Production
                echo "Deployment successful, model promoted to Production"
              displayName: 'Promote model to Production'